site_name: Language styles

site_url: https://WNHS-Safety-and-Quality.github.io/language-styles
theme:
  name: material


nav:
  - "C#":
    - Implicitly-typed local variables: "csharp/var.md"
    - Et cetera: "csharp/etc.md"


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences